# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* sign_itsme
# 
# Translators:
# Wil Odoo, 2023
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 17.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-10-26 22:21+0000\n"
"PO-Revision-Date: 2023-10-26 23:10+0000\n"
"Last-Translator: Wil Odoo, 2023\n"
"Language-Team: Arabic (https://app.transifex.com/odoo/teams/41243/ar/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: ar\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"

#. module: sign_itsme
#: model_terms:ir.ui.view,arch_db:sign_itsme.sign_request_logs_user
msgid ""
"<small>Name: The signatory has provided this identity through itsme®</small>"
msgstr "<small>الاسم: قدم الطرف الموقّع هذه الهوية عن طريق itsme®</small> "

#. module: sign_itsme
#: model:sign.item.role,name:sign_itsme.sign_item_role_itsme_customer
msgid "Customer (identified with itsme®)"
msgstr "العميل (معرَّف باستخدام itsme®) "

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/components/document_signable.js:0
#, python-format
msgid "Error"
msgstr "خطأ"

#. module: sign_itsme
#: model:ir.model.fields,field_description:sign_itsme.field_sign_item_role__auth_method
msgid "Extra Authentication Step"
msgstr "خطوة المصادقة الإضافية "

#. module: sign_itsme
#: model:ir.model.fields,help:sign_itsme.field_sign_item_role__auth_method
msgid "Force the signatory to identify using a second authentication method"
msgstr "إجبار الطرف الموقّع على التعريف باستخدام وسيلة مصادقة ثانية "

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/dialogs/itsme_dialog.xml:0
#, python-format
msgid "Go Back"
msgstr "عد"

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/components/document_signable.js:0
#, python-format
msgid "Identification refused"
msgstr "تم رفض التعريف "

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/dialogs/itsme_dialog.xml:0
#, python-format
msgid "Identify with itsme"
msgstr "التعريف باستخدام itsme "

#. module: sign_itsme
#: model_terms:ir.ui.view,arch_db:sign_itsme.sign_request_logs_user
msgid "Name"
msgstr "الاسم"

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/dialogs/itsme_dialog.xml:0
#, python-format
msgid "Please confirm your identity to finalize your signature."
msgstr "يرجى تأكيد هويتك للانتهاء من توقيعك. "

#. module: sign_itsme
#. odoo-python
#: code:addons/sign_itsme/models/sign_request_item.py:0
#, python-format
msgid "Sign request item is not validated yet."
msgstr "لم يتم تصديق عنصر أمر التوقيع بعد. "

#. module: sign_itsme
#: model:ir.model,name:sign_itsme.model_sign_item_role
msgid "Signature Item Party"
msgstr "جهة عنصر التوقيع "

#. module: sign_itsme
#: model:ir.model,name:sign_itsme.model_sign_request
msgid "Signature Request"
msgstr "طلب التوقيع"

#. module: sign_itsme
#: model:ir.model,name:sign_itsme.model_sign_request_item
msgid "Signature Request Item"
msgstr "عنصر طلب التوقيع"

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/components/document_signable.js:0
#, python-format
msgid ""
"The itsme® identification data could not be forwarded to Odoo, the signature"
" could not be saved."
msgstr "تعذر إعادة توجيه بيانات تعريف itsme®. لم نتمكن من حفظ التوقيع. "

#. module: sign_itsme
#: model:ir.model.fields.selection,name:sign_itsme.selection__sign_item_role__auth_method__itsme
msgid "Via itsme®"
msgstr "عن طريق itsme® "

#. module: sign_itsme
#. odoo-javascript
#: code:addons/sign_itsme/static/src/components/document_signable.js:0
#, python-format
msgid ""
"You have rejected the identification request or took too long to process it."
" You can try again to finalize your signature."
msgstr ""
"لقد قمت برفض طلب التعريف أو قد تكون استغرقت وقتاً طويلاً لمعالجته. بإمكانك "
"المحاولة مجدداً لاحقاً للانتهاء من توقيعك. "

#. module: sign_itsme
#. odoo-python
#: code:addons/sign_itsme/controllers/main.py:0
#, python-format
msgid "itsme® IAP service could not be found."
msgstr "لم يتم العثور على خدمة عمليات الشراء داخل التطبيق في itsme®. "

#. module: sign_itsme
#: model:ir.model.fields,field_description:sign_itsme.field_sign_request_item__itsme_signer_birthdate
msgid "itsme® Signer's Birthdate"
msgstr "تاريخ ميلاد الموقّع في itsme® "

#. module: sign_itsme
#: model:ir.model.fields,field_description:sign_itsme.field_sign_request_item__itsme_signer_name
msgid "itsme® Signer's Name"
msgstr "اسم الموقّع في itsme® "

#. module: sign_itsme
#: model:ir.model.fields,field_description:sign_itsme.field_sign_request_item__itsme_validation_hash
msgid "itsme® Validation Token"
msgstr "رمز التحقق في itsme® "
